sudo: required
dist: trusty
before_install:
    - wget "https://github.com/0X1A/yabs/releases/download/0.2.1/yabs_0.2.1_amd64.deb"
    - sudo dpkg -i yabs_0.2.1_amd64.deb
    - git submodule update --init
    - sed -i 's/lua5\.3/lua5\.1/g' kuma.toml tests/tests.toml
    - sudo apt-get update -qq
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install gcc-6 g++-6 -y
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
    - sudo apt-get install build-essential valgrind libsdl2-ttf-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libboost-dev liblua5.1-0-dev libyaml-cpp-dev -y
script:
    - yabs build
